import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body>
        <header>
          <ul>
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/list'>List</Link></li>
            <li><Link href='/write'>Write</Link></li>
          </ul>

        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
